FROM openjdk:11

# copy the packaged jar file into our docker image
COPY target/CoTransfer-0.0.1-SNAPSHOT.jar /CoTransfer.jar

# set the startup command to execute the jar file
CMD ["java", "-jar", "/CoTransfer.jar"]